#!/usr/bin/env python3
"""Generate `qrss_beacon_c/qrss_tables.h`, the constant tables of the C
reference beacon (design section 9).

    tools/gen_qrss_tables.py            # rewrite qrss_beacon_c/qrss_tables.h
    tools/gen_qrss_tables.py --check    # exit 1 unless the file is current
    tools/gen_qrss_tables.py --stdout   # print it instead

**Generated and committed**, like `native/core/config.hpp`: committed so
a microcontroller build needs no Python, generated so the C never holds a
hand-copied on-air number. Everything comes from `sstvae.qrss`:

- `QRSS_PULSE_Q14[513]`: the CE pulse p(k/64), k = 0..512 (0 to 8
  symbols at T/64), in Q14. Q15 would overflow, since p(0) = 1.041. The
  pulse is symmetric, so this half-table plus linear interpolation is the
  whole of it (8e-5 rad rms phase error, design 9).
- `QRSS_HANN_R_Q30[65]`: R(y), the integral of the Hann CDF, at
  y = -1/2 + k/64, in Q30 turns. It shapes the FSK callsign windows.
- `QRSS_SCALE_Q32[8]`: turns of phase per unit symbol value: index 0 is
  beta/(2 pi) for the +-1 symbols (preamble, references, header), index
  1 + log2(M) is beta/(2 pi 20 sqrt(M)) for a data symbol of a size-M
  precoder block, whose integer value is the unnormalised WHT of the
  sign-flipped int8 latents.
- `QRSS_SPREAD_Q32`: beta sqrt(SPREAD_RHO)/(2 pi), the turns of phase of
  the spread copy of the header on a data symbol (spec 5.1, format
  version 2), whose value there is +-1.
- The frame presets of `frame.PRESETS` (header length, data latents,
  callsign windows, whether the data carry the spread copy), so the slot timing stays one edit in `frame.py`
  followed by a regeneration -- `--check` catches a forgotten one.
- The SHA-256 domain strings, the symbol clock and the window geometry.
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from sstvae.qrss import ce, constants as C, frame, sequences  # noqa: E402

OUT = ROOT / "qrss_beacon_c" / "qrss_tables.h"
PULSE_STEPS = 64                    # table points per symbol
HANN_STEPS = 64                     # table points per Morse unit
MAX_WINDOWS = 4                     # windows a preset may have in the C struct


def pulse_q14() -> np.ndarray:
    k = np.arange(C.SPAN * PULSE_STEPS + 1)
    return np.rint(ce.pulse(k / PULSE_STEPS) * (1 << 14)).astype(np.int64)


def hann_r_q30() -> np.ndarray:
    y = -0.5 + np.arange(HANN_STEPS + 1) / HANN_STEPS
    return np.rint(ce._hann_int(y) * (1 << 30)).astype(np.int64)


def scale_q32() -> np.ndarray:
    beta = float(C.BETA)
    vals = [beta / (2 * math.pi)]
    vals += [beta / (2 * math.pi * C.INT8_SCALE * math.sqrt(1 << b)) for b in range(7)]
    return np.rint(np.array(vals) * 2.0 ** 32).astype(np.int64)


def spread_q32() -> int:
    return int(np.rint(float(C.BETA) * math.sqrt(C.SPREAD_RHO) / (2 * math.pi) * 2.0 ** 32))


def _rows(vals, per_line: int, fmt: str) -> str:
    items = [fmt.format(int(v)) for v in vals]
    lines = [", ".join(items[i:i + per_line]) for i in range(0, len(items), per_line)]
    return ",\n    ".join(lines)


def _cstr(b: bytes) -> str:
    return '"' + b.decode("ascii") + '"'


def render() -> str:
    p = pulse_q14()
    r = hann_r_q30()
    s = scale_q32()
    spread = spread_q32()
    assert p.max() < (1 << 15) and r.max() < (1 << 31) and s.max() < (1 << 31)
    assert 0 < spread < (1 << 31)
    presets = []
    for spec in frame.PRESETS.values():
        if spec.n_win > MAX_WINDOWS:
            raise SystemExit(f"preset {spec.name} has {spec.n_win} windows; "
                             f"the C struct holds {MAX_WINDOWS}")
        if spec.hdr_rho not in (0.0, C.SPREAD_RHO):
            raise SystemExit(f"preset {spec.name} has hdr_rho {spec.hdr_rho}; the C "
                             f"sends the spread copy at SPREAD_RHO or not at all")
        cw = list(spec.cw_after) + [0] * (MAX_WINDOWS - spec.n_win)
        presets.append(f'    {{"{spec.name}", {spec.n_hdr}u, {spec.n_data}u, '
                       f'{spec.n_win}u, {{{", ".join(f"{c}u" for c in cw)}}}, '
                       f'{int(spec.hdr_rho > 0)}u}}')
    return f"""\
/* qrss_tables.h -- GENERATED by tools/gen_qrss_tables.py; do not edit.
 *
 * Constant tables of the QRSSTVAE CE reference beacon, derived from
 * sstvae/qrss (design section 9). Regenerate with
 *     python tools/gen_qrss_tables.py
 * and check with --check.
 */
#ifndef QRSS_TABLES_H
#define QRSS_TABLES_H

#include <stdint.h>

/* Symbol clock: T = QRSS_T_NUM / QRSS_T_DEN s. */
#define QRSS_T_NUM          {C.T_NUM}u
#define QRSS_T_DEN          {C.T_DEN}u
#define QRSS_SPAN           {C.SPAN}           /* pulse cut, symbols */

/* Frame building blocks. */
#define QRSS_N_PRE          {C.N_PRE}u
#define QRSS_N_HDR          {C.N_HDR}u
#define QRSS_N_HDR_BITS     {C.N_HDR_BITS}u
#define QRSS_REF_PERIOD     {C.REF_PERIOD}u
#define QRSS_MAX_LATENTS    {frame.FULL.n_data}u
#define QRSS_INT8_SCALE     {C.INT8_SCALE}u
#define QRSS_WAVEFORM_CE    {C.WAVEFORM_CE}u

/* Callsign windows (spec 2.7). */
#define QRSS_CW_WINDOW      {C.CW_WINDOW}u     /* symbols per window */
#define QRSS_CW_UNIT        {C.CW_UNIT}u       /* symbols per Morse unit */
#define QRSS_CW_UNITS       {C.CW_UNITS}u     /* units per window */
#define QRSS_CW_LEAD_UNITS  {C.CW_LEAD_UNITS}u
#define QRSS_CW_ROOM_UNITS  {C.CW_ROOM_UNITS}u
#define QRSS_OOK_FIRST_UNIT {ce.OOK_FIRST_KEYED_UNIT}u
#define QRSS_OOK_LAST_UNIT  {ce.OOK_LAST_KEYED_UNIT}u
#define QRSS_MAX_WINDOWS    {MAX_WINDOWS}u

/* SHA-256 domain strings (ASCII, no terminator on air). */
#define QRSS_PREAMBLE_DOMAIN  {_cstr(sequences.PREAMBLE_DOMAIN)}
#define QRSS_REFERENCE_DOMAIN {_cstr(sequences.REFERENCE_DOMAIN)}
#define QRSS_SCRAMBLE_DOMAIN  {_cstr(sequences.SCRAMBLE_DOMAIN)}
#define QRSS_SPREAD_DOMAIN    {_cstr(sequences.SPREAD_DOMAIN)}

/* p(k/{PULSE_STEPS}) in Q14, k = 0..{C.SPAN * PULSE_STEPS}. */
#define QRSS_PULSE_STEPS {PULSE_STEPS}
static const int16_t QRSS_PULSE_Q14[{len(p)}] = {{
    {_rows(p, 12, "{:6d}")}
}};

/* R(y) at y = -1/2 + k/{HANN_STEPS}, k = 0..{HANN_STEPS}, in Q30 turns. */
#define QRSS_HANN_STEPS {HANN_STEPS}
static const int32_t QRSS_HANN_R_Q30[{len(r)}] = {{
    {_rows(r, 6, "{:10d}")}
}};

/* Turns per unit symbol value, Q32: [0] beta/(2 pi) for +-1 symbols;
 * [1 + log2 M] beta/(2 pi 20 sqrt M) for data in a size-M block. */
static const int32_t QRSS_SCALE_Q32[8] = {{
    {_rows(s, 4, "{:10d}")}
}};

/* Turns per unit of the spread header on a data symbol, Q32:
 * beta sqrt(rho)/(2 pi), rho = {C.SPREAD_RHO} (spec 5.1). */
#define QRSS_SPREAD_Q32 {spread}

/* Frame presets (frame.PRESETS): name, n_hdr, n_data, n_win, cw_after,
 * spread (1: the data carry the spread copy of the header, format
 * version 2; every preset with a header block does). */
typedef struct {{
    const char *name;
    uint32_t n_hdr;
    uint32_t n_data;
    uint32_t n_win;
    uint32_t cw_after[QRSS_MAX_WINDOWS];
    uint32_t spread;
}} qrss_frame_t;

#define QRSS_N_PRESETS {len(presets)}
static const qrss_frame_t QRSS_PRESETS[QRSS_N_PRESETS] = {{
{",\n".join(presets)}
}};

#endif /* QRSS_TABLES_H */
"""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 unless qrss_tables.h equals what would be generated")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    ap.add_argument("--out", type=Path, default=OUT, help="output path (default %(default)s)")
    args = ap.parse_args(argv)

    text = render()
    if args.stdout:
        sys.stdout.write(text)
        return 0
    if args.check:
        current = args.out.read_text() if args.out.exists() else None
        if current != text:
            print(f"{args.out} is stale: run tools/gen_qrss_tables.py", file=sys.stderr)
            return 1
        print(f"{args.out} is current")
        return 0
    args.out.write_text(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
